### PR TITLE
Moved infractions off the user and onto the guild with a key to the user

### PR DESCRIPTION
**Pull request by VelvetToroyashi**
It is easier to track guild-level cases without having to traverse the entire database to pull up what infractions occurred on a given guild, and thus it was moved.

Along with that, IDatabaseService, and it's concrete implementation have been removed. Some slight improvements have been made to the InfractionService, and multiple UserFlags have been removed, causing their values to differ. 

This will be pushed as part of 1.4, and with further testing, cleanup, and hopefully more Unit Tests, we will precede to push to master/prod. cc @NatsumiHB and @CalebABG, let me know if any changes need to be made.

### CODE REVIEW

**Review by OoLunar — APPROVED** [review]
Looks good.

**Review by CalebABG — APPROVED** [review]
In the DailyCommand, before you send the MediatR request to update the users cash, you update the user object's cash amount; could replace with setting the Cash property on the request model to the users current cash plus the daily amount since the user is going to be updated in the handler

**Comment by VelvetToroyashi** [comment]
Done

**Review by ghost — COMMENTED** [review]
Yes gud I like

**Pull request merged**
